### SIGNUP
POST http://localhost:5000/api/v1/signup/
Content-Type: application/json

{
    "fullname"  : "Pandu",
    "username"  : "pandu",
    "email"     : "pandu@gmail.com",
    "password"  : "pandu"
}

### SIGN
POST http://localhost:5000/api/v1/sign/
Content-Type: application/json

{
    "email"     : "pandu@gmail.com",
    "password"  : "pandu"
}