### SIGNUP
POST http://localhost:5000/api/v1/signup/
Content-Type: application/json

{
    "fullname"  : "Abdillah F",
    "username"  : "siunix",
    "email"     : "siunixdev@gmail.com",
    "password"  : "siunix"
}

### SIGN
POST http://localhost:5000/api/v1/sign/
Content-Type: application/json

{
    "email"     : "siunixdev@gmail.com",
    "password"  : "siunix"
}