## CATEGORY

### LIST
GET http://localhost:5000/api/v1/categories/

### DETAIL
GET http://localhost:5000/api/v1/category/26


### SAVE
POST http://localhost:5000/api/v1/category/
Content-Type: application/json
Authorization : bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTIsImlhdCI6MTU3NzIxMTAzNH0.788FeaUqGBW31wRI1__gpbN9wfrHmmZAussH8PsgvzE

{
    "name" : "More"
}

### UPDATE
PATCH http://localhost:5000/api/v1/category/9
Content-Type: application/json
Authorization : bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTIsImlhdCI6MTU3NzIxMTAzNH0.788FeaUqGBW31wRI1__gpbN9wfrHmmZAussH8PsgvzE

{
    "name" : "Human Parts"
}

### DELETE
DELETE http://localhost:5000/api/v1/category/15
Authorization : bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTIsImlhdCI6MTU3NzIxMTAzNH0.788FeaUqGBW31wRI1__gpbN9wfrHmmZAussH8PsgvzE